### ISSUE TITLE
After uninstalling py5mode on Windows, Thonny is broken

### ISSUE THREAD

**Issue by codeanticode** [tabreturn/thonny-py5mode#19]
I uninstalled py5mode, and upon restarting Thonny I got the following error:

![image](https://user-images.githubusercontent.com/62246/167407041-22354397-a04c-4eb6-9a33-59b91050195a.png)

After closing this error, the IDE is frozen.

But then I uninstalled and re-installed Thonny, and the same error comes up - I even manually deleted the AppData/Local/Programs/Thonny folder before uninstalling and still the same error comes up, so effectively making Thonny unusable. Tested on Windows 10.

**Comment by tabreturn** [comment]
You're using Windows, I assume? Delete the `\AppData\Roaming\Thonny` folder (or, more specifically, edit/delete the *configuration.ini* file therein).

Thonny won't default to another theme if the one you've applied is missing. By uninstalling thonny-py5mode, you've effectively deleted the active theme (Kyanite). However, this issue is fixed in Thonny 4: https://github.com/thonny/thonny/issues/2149

Note that thonny-py5mode won't run on Thonny 4 until JPype adds wheels for Python 3.10 (probably quite soon).
